[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    Cache-Control = "private, must-revalidate"
    Content-Security-Policy = "frame-ancestors 'none'; form-action 'self';"
